{
  "resource_transfer": {
    "China": {
      "Japan": {
        "silicon": 10
      }
    }
  },
  "countries": {
    "China": {
      "has_mine": true,
      "has_plant": false,
      "silicon_export_rate": 0.8, 
      "processing_capacity": 0.2
    },
    "Japan": {
      "has_mine": true,
      "has_plant": true,
      "silicon_export_rate": 0.1,
      "processing_capacity": 0.9
    },
    "US": {
      "has_mine": true,
      "has_plant": false,
      "silicon_export_rate": 0,
      "processing_capacity": 0
    },
    "EU": {
      "has_mine": true,
      "has_plant": false,
      "silicon_export_rate": 0,
      "processing_capacity": 0
    },
    "Taiwan": {
      "has_mine": true,
      "has_plant": false,
      "silicon_export_rate": 0,
      "processing_capacity": 0
    }
  }
}

  