resource_transfer: 
  China: 
    Japan: 
      silicon: 10
countries: 
  China: 
    mines: 10
    plants: 0
    silicon_export_rate: 0.8
    processing_capacity: 0.2
  Japan: 
    mines: 2
    plants: 10
    silicon_export_rate: 0.1
    processing_capacity: 0.9
  US: 
    mines: 4
    plants: 1
    silicon_export_rate: 0
    processing_capacity: 0
  EU: 
    mines: 4
    plants: 4
    silicon_export_rate: 0
    processing_capacity: 0
  Taiwan: 
    mines: 1
    plants: 1
    silicon_export_rate: 0
    processing_capacity: 0
additional_companies: 10
CompanyAgent:
  money_range: [100, 1000]
  chips_range: [100, 1000]
  talent_range: [1, 10]


company_country_map:
  US: [Nvidia, Intel]
  Taiwan: [TSMC, MediaTek]
  China: [SMIC, HuaHong]
  EU: [Infineon, STMicroelectronics]
  Japan: [Renesas, Sony]


partnerships:
  - [Nvidia, TSMC]
