CompanyAgent: 
  lookback_steps: 5
  talent_range: [1, 10]
  influence: 0.5
  initial_resources: 
    money: 100
    chips: 50
  cooperation_thresholds: 
    money: 30
    chips: 30
  project_launch_cost: 10
  project_launch_threshold: 10
  government_lobby_money_threshold: 50
  government_lobby_talent_threshold: 5
  competition_percentage: 0.1
  Nvidia:
    talent_range: [5, 10]
    initial_resources: {'money': 10000, 'chips': 100, 'services': 2}#is the 100 redundant now that i have the chips in stock function?
    # more Nvidia-specific configurations here...
  Intel:
    talent_range: [5, 10]
    initial_resources: {'money': 100, 'chips': 100, 'services': 2, 'wafers': 100}
    # more Nvidia-specific configurations here...
  CustomerAgent:
    talent_range: [5, 10]
    initial_resources: {'money': 1000, 'chips': 100, 'services': 2, 'wafers': 100}
    order_range: [50,100]
    # more Nvidia-specific configurations here...
  FabIntel:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150, 'services': 500, 'wafers': 500}
  TSMC:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150, 'services': 500, 'wafers': 500}
    # more TSMC-specific configurations here...
  ASML:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150, 'services': 2}
    # more TSMC-specific configurations here...
  Samsung:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150, 'services': 2, 'wafers': 500}
  SamsungSub:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150, 'services': 2, 'wafers': 500}
  MediaTek:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150} 
    # more TSMC-specific configurations here...
  Infineon:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150}
    # more Infineon-specific configurations here...
  STMicroelectronics:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150}
    # more Infineon-specific configurations here...
  Renesas:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150}
    # more Renesas-specific configurations here...
  Sony:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150}
    # more Renesas-specific configurations here...
  SMIC:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150}
    # more SMIC-specific configurations here...
  HuaHong:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150}
    # more Huahong-specific configurations here...
  Sumco:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 0, 'wafers': 150}
    # more Sumco-specific configurations here...
  SKSiltron:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 0, 'wafers': 150, 'silicon': 3}
    # more SKSiltron-specific configurations here...
  Siltronic:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 0, 'wafers': 150, 'services': 0}
    # more Siltronic-specific configurations here...
  Fujimi:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 0, 'services': 100, 'silicon': 0}
    # more Fujimi-specific configurations here...
  ShinEtsu:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 0, 'services': 0, 'silicon': 500}
    # more Fujimi-specific configurations here...
CountryAgent: 
  initial_resources: 
    money: 100
    chips: 50
    silicon: 0
  sanctions_cost: 30
  sanctions_percentage: 0.2
  alliance_cost: 20
  alliance_gain: 10
  research_investment_cost: 15
  research_capacity_gain: 10
  cooperation_thresholds: 
    money: 30
    chips: 30
  decision_thresholds: 
    money: [30, 60]
    chips: [20, 30]
    anxiety_score: [7]
    gdp: [5]
MineAgent: 
  initial_resources: 
    silicon: 100
    money: 50
    chips: 0
ProcessingPlantAgent: 
  initial_resources: 
    chips: 50
    money: 50
    silicon: 0
