CompanyAgent: 
  talent_range: [1, 10]
  influence: 1
  initial_resources: 
    money: 100
    chips: 50
  cooperation_thresholds: 
    money: 30
    chips: 30
  project_launch_cost: 10
  project_launch_threshold: 10
  government_lobby_money_threshold: 50
  government_lobby_talent_threshold: 5
  competition_percentage: 0.1
  Nvidia:
    talent_range: [5, 10]
    initial_resources: {'money': 100, 'chips': 100}
    # more Nvidia-specific configurations here...
  Intel:
    talent_range: [5, 10]
    initial_resources: {'money': 100, 'chips': 100}
    # more Nvidia-specific configurations here...
  TSMC:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150}
    # more TSMC-specific configurations here...
  MediaTek:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150}
    # more TSMC-specific configurations here...
  Infineon:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150}
    # more Infineon-specific configurations here...
  STMicroelectronics:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150}
    # more Infineon-specific configurations here...
  Renesas:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150}
    # more Renesas-specific configurations here...
  Sony:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150}
    # more Renesas-specific configurations here...
  SMIC:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150}
    # more SMIC-specific configurations here...
  HuaHong:
    talent_range: [7, 12]
    initial_resources: {'money': 150, 'chips': 150}
    # more SMIC-specific configurations here...
CountryAgent: 
  initial_resources: 
    money: 100
    chips: 50
    silicon: 0
  sanctions_cost: 30
  sanctions_percentage: 0.2
  alliance_cost: 20
  alliance_gain: 10
  research_investment_cost: 15
  research_capacity_gain: 10
  cooperation_thresholds: 
    money: 30
    chips: 30
  decision_thresholds: 
    money: [30, 60]
    chips: [20, 30]
    anxiety_score: [7]
    gdp: [5]
MineAgent: 
  initial_resources: 
    silicon: 100
    money: 50
    chips: 0
ProcessingPlantAgent: 
  initial_resources: 
    chips: 50
    money: 50
    silicon: 0
